# Generated by Django 6.0.4 on 2026-04-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('mueble', 'Mueble')], max_length=20)),
                ('m2', models.IntegerField(blank=True, null=True)),
                ('planos', models.FileField(blank=True, null=True, upload_to='planos/')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
