# Generated by Django 5.1 on 2026-05-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='planos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
